ga:
  num_generations: [50]
  population_size: [50, 150]
  selection_type: ["tournament", "sss"]
  crossover_type: ["single_point", "two_points"]
  mutation_type: ["random", "adaptive"]
  crossover_probability: [0.8]
  mutation_probability: [0.2]
  elitism: [2]
